version: "3.8"
services:
  webserver:
    image: shopaction-backend
    build:
      context: ../../ShopAction
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 5009:5009
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5009
      - ConnectionStrings:ShopAction=Server=192.168.1.163,14333;Database=ShopActionDb;MultipleActiveResultSets=true;User ID=sa;Password=P@ssw0rd
    restart: on-failure