version: "3.8"
services:
  webserver:
    image: shopaction-backend
    build:
      context: ../../ShopAction
      dockerfile: Dockerfile
    ports:
      - 5001:5001
    environment:
      - ASPNETCORE_ENVIRONMENT=Debug
      - ConnectionStrings:DefaultConnection=Server=192.168.1.4,14333;Database=CleanArchitectureDb;MultipleActiveResultSets=true;User ID=sa;Password=P@ssw0rd
      - ASPNETCORE_URLS=http://+:5001
    restart: on-failure
