version: "3.8"
services:
  local-db:
    image: "mcr.microsoft.com/mssql/server"
    ports:
      - "14333:1433"
    environment:
      SA_PASSWORD: "P@ssw0rd"
      ACCEPT_EULA: "Y"
    volumes:
      - type: volume
        source: mssql-server-linux-data
        target: /var/opt/mssql
    restart: on-failure
  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - mssql-server-linux-data:/data
volumes:
  mssql-server-linux-data:
